/******************************************************************************
*  Generated by PSoC Designer 5.1.2306
******************************************************************************/
#include <m8c.h>
// UART_TX address and mask defines
#pragma	ioport	UART_TX_Data_ADDR:	0x0
BYTE			UART_TX_Data_ADDR;
#pragma	ioport	UART_TX_DriveMode_0_ADDR:	0x100
BYTE			UART_TX_DriveMode_0_ADDR;
#pragma	ioport	UART_TX_DriveMode_1_ADDR:	0x101
BYTE			UART_TX_DriveMode_1_ADDR;
#pragma	ioport	UART_TX_DriveMode_2_ADDR:	0x3
BYTE			UART_TX_DriveMode_2_ADDR;
#pragma	ioport	UART_TX_GlobalSelect_ADDR:	0x2
BYTE			UART_TX_GlobalSelect_ADDR;
#pragma	ioport	UART_TX_IntCtrl_0_ADDR:	0x102
BYTE			UART_TX_IntCtrl_0_ADDR;
#pragma	ioport	UART_TX_IntCtrl_1_ADDR:	0x103
BYTE			UART_TX_IntCtrl_1_ADDR;
#pragma	ioport	UART_TX_IntEn_ADDR:	0x1
BYTE			UART_TX_IntEn_ADDR;
#define UART_TX_MASK 0x1
// ADC_SINN address and mask defines
#pragma	ioport	ADC_SINN_Data_ADDR:	0x0
BYTE			ADC_SINN_Data_ADDR;
#pragma	ioport	ADC_SINN_DriveMode_0_ADDR:	0x100
BYTE			ADC_SINN_DriveMode_0_ADDR;
#pragma	ioport	ADC_SINN_DriveMode_1_ADDR:	0x101
BYTE			ADC_SINN_DriveMode_1_ADDR;
#pragma	ioport	ADC_SINN_DriveMode_2_ADDR:	0x3
BYTE			ADC_SINN_DriveMode_2_ADDR;
#pragma	ioport	ADC_SINN_GlobalSelect_ADDR:	0x2
BYTE			ADC_SINN_GlobalSelect_ADDR;
#pragma	ioport	ADC_SINN_IntCtrl_0_ADDR:	0x102
BYTE			ADC_SINN_IntCtrl_0_ADDR;
#pragma	ioport	ADC_SINN_IntCtrl_1_ADDR:	0x103
BYTE			ADC_SINN_IntCtrl_1_ADDR;
#pragma	ioport	ADC_SINN_IntEn_ADDR:	0x1
BYTE			ADC_SINN_IntEn_ADDR;
#define ADC_SINN_MASK 0x2
// PWM2 address and mask defines
#pragma	ioport	PWM2_Data_ADDR:	0x0
BYTE			PWM2_Data_ADDR;
#pragma	ioport	PWM2_DriveMode_0_ADDR:	0x100
BYTE			PWM2_DriveMode_0_ADDR;
#pragma	ioport	PWM2_DriveMode_1_ADDR:	0x101
BYTE			PWM2_DriveMode_1_ADDR;
#pragma	ioport	PWM2_DriveMode_2_ADDR:	0x3
BYTE			PWM2_DriveMode_2_ADDR;
#pragma	ioport	PWM2_GlobalSelect_ADDR:	0x2
BYTE			PWM2_GlobalSelect_ADDR;
#pragma	ioport	PWM2_IntCtrl_0_ADDR:	0x102
BYTE			PWM2_IntCtrl_0_ADDR;
#pragma	ioport	PWM2_IntCtrl_1_ADDR:	0x103
BYTE			PWM2_IntCtrl_1_ADDR;
#pragma	ioport	PWM2_IntEn_ADDR:	0x1
BYTE			PWM2_IntEn_ADDR;
#define PWM2_MASK 0x8
// PWM1 address and mask defines
#pragma	ioport	PWM1_Data_ADDR:	0x0
BYTE			PWM1_Data_ADDR;
#pragma	ioport	PWM1_DriveMode_0_ADDR:	0x100
BYTE			PWM1_DriveMode_0_ADDR;
#pragma	ioport	PWM1_DriveMode_1_ADDR:	0x101
BYTE			PWM1_DriveMode_1_ADDR;
#pragma	ioport	PWM1_DriveMode_2_ADDR:	0x3
BYTE			PWM1_DriveMode_2_ADDR;
#pragma	ioport	PWM1_GlobalSelect_ADDR:	0x2
BYTE			PWM1_GlobalSelect_ADDR;
#pragma	ioport	PWM1_IntCtrl_0_ADDR:	0x102
BYTE			PWM1_IntCtrl_0_ADDR;
#pragma	ioport	PWM1_IntCtrl_1_ADDR:	0x103
BYTE			PWM1_IntCtrl_1_ADDR;
#pragma	ioport	PWM1_IntEn_ADDR:	0x1
BYTE			PWM1_IntEn_ADDR;
#define PWM1_MASK 0x20
// PWM0 address and mask defines
#pragma	ioport	PWM0_Data_ADDR:	0x0
BYTE			PWM0_Data_ADDR;
#pragma	ioport	PWM0_DriveMode_0_ADDR:	0x100
BYTE			PWM0_DriveMode_0_ADDR;
#pragma	ioport	PWM0_DriveMode_1_ADDR:	0x101
BYTE			PWM0_DriveMode_1_ADDR;
#pragma	ioport	PWM0_DriveMode_2_ADDR:	0x3
BYTE			PWM0_DriveMode_2_ADDR;
#pragma	ioport	PWM0_GlobalSelect_ADDR:	0x2
BYTE			PWM0_GlobalSelect_ADDR;
#pragma	ioport	PWM0_IntCtrl_0_ADDR:	0x102
BYTE			PWM0_IntCtrl_0_ADDR;
#pragma	ioport	PWM0_IntCtrl_1_ADDR:	0x103
BYTE			PWM0_IntCtrl_1_ADDR;
#pragma	ioport	PWM0_IntEn_ADDR:	0x1
BYTE			PWM0_IntEn_ADDR;
#define PWM0_MASK 0x80
// SSI_CS address and mask defines
#pragma	ioport	SSI_CS_Data_ADDR:	0x4
BYTE			SSI_CS_Data_ADDR;
#pragma	ioport	SSI_CS_DriveMode_0_ADDR:	0x104
BYTE			SSI_CS_DriveMode_0_ADDR;
#pragma	ioport	SSI_CS_DriveMode_1_ADDR:	0x105
BYTE			SSI_CS_DriveMode_1_ADDR;
#pragma	ioport	SSI_CS_DriveMode_2_ADDR:	0x7
BYTE			SSI_CS_DriveMode_2_ADDR;
#pragma	ioport	SSI_CS_GlobalSelect_ADDR:	0x6
BYTE			SSI_CS_GlobalSelect_ADDR;
#pragma	ioport	SSI_CS_IntCtrl_0_ADDR:	0x106
BYTE			SSI_CS_IntCtrl_0_ADDR;
#pragma	ioport	SSI_CS_IntCtrl_1_ADDR:	0x107
BYTE			SSI_CS_IntCtrl_1_ADDR;
#pragma	ioport	SSI_CS_IntEn_ADDR:	0x5
BYTE			SSI_CS_IntEn_ADDR;
#define SSI_CS_MASK 0x8
// SSI_DCLK address and mask defines
#pragma	ioport	SSI_DCLK_Data_ADDR:	0x4
BYTE			SSI_DCLK_Data_ADDR;
#pragma	ioport	SSI_DCLK_DriveMode_0_ADDR:	0x104
BYTE			SSI_DCLK_DriveMode_0_ADDR;
#pragma	ioport	SSI_DCLK_DriveMode_1_ADDR:	0x105
BYTE			SSI_DCLK_DriveMode_1_ADDR;
#pragma	ioport	SSI_DCLK_DriveMode_2_ADDR:	0x7
BYTE			SSI_DCLK_DriveMode_2_ADDR;
#pragma	ioport	SSI_DCLK_GlobalSelect_ADDR:	0x6
BYTE			SSI_DCLK_GlobalSelect_ADDR;
#pragma	ioport	SSI_DCLK_IntCtrl_0_ADDR:	0x106
BYTE			SSI_DCLK_IntCtrl_0_ADDR;
#pragma	ioport	SSI_DCLK_IntCtrl_1_ADDR:	0x107
BYTE			SSI_DCLK_IntCtrl_1_ADDR;
#pragma	ioport	SSI_DCLK_IntEn_ADDR:	0x5
BYTE			SSI_DCLK_IntEn_ADDR;
#define SSI_DCLK_MASK 0x20
// SSI_DIO address and mask defines
#pragma	ioport	SSI_DIO_Data_ADDR:	0x4
BYTE			SSI_DIO_Data_ADDR;
#pragma	ioport	SSI_DIO_DriveMode_0_ADDR:	0x104
BYTE			SSI_DIO_DriveMode_0_ADDR;
#pragma	ioport	SSI_DIO_DriveMode_1_ADDR:	0x105
BYTE			SSI_DIO_DriveMode_1_ADDR;
#pragma	ioport	SSI_DIO_DriveMode_2_ADDR:	0x7
BYTE			SSI_DIO_DriveMode_2_ADDR;
#pragma	ioport	SSI_DIO_GlobalSelect_ADDR:	0x6
BYTE			SSI_DIO_GlobalSelect_ADDR;
#pragma	ioport	SSI_DIO_IntCtrl_0_ADDR:	0x106
BYTE			SSI_DIO_IntCtrl_0_ADDR;
#pragma	ioport	SSI_DIO_IntCtrl_1_ADDR:	0x107
BYTE			SSI_DIO_IntCtrl_1_ADDR;
#pragma	ioport	SSI_DIO_IntEn_ADDR:	0x5
BYTE			SSI_DIO_IntEn_ADDR;
#define SSI_DIO_MASK 0x80
// PWM5 address and mask defines
#pragma	ioport	PWM5_Data_ADDR:	0x8
BYTE			PWM5_Data_ADDR;
#pragma	ioport	PWM5_DriveMode_0_ADDR:	0x108
BYTE			PWM5_DriveMode_0_ADDR;
#pragma	ioport	PWM5_DriveMode_1_ADDR:	0x109
BYTE			PWM5_DriveMode_1_ADDR;
#pragma	ioport	PWM5_DriveMode_2_ADDR:	0xb
BYTE			PWM5_DriveMode_2_ADDR;
#pragma	ioport	PWM5_GlobalSelect_ADDR:	0xa
BYTE			PWM5_GlobalSelect_ADDR;
#pragma	ioport	PWM5_IntCtrl_0_ADDR:	0x10a
BYTE			PWM5_IntCtrl_0_ADDR;
#pragma	ioport	PWM5_IntCtrl_1_ADDR:	0x10b
BYTE			PWM5_IntCtrl_1_ADDR;
#pragma	ioport	PWM5_IntEn_ADDR:	0x9
BYTE			PWM5_IntEn_ADDR;
#define PWM5_MASK 0x20
// PWM4 address and mask defines
#pragma	ioport	PWM4_Data_ADDR:	0x8
BYTE			PWM4_Data_ADDR;
#pragma	ioport	PWM4_DriveMode_0_ADDR:	0x108
BYTE			PWM4_DriveMode_0_ADDR;
#pragma	ioport	PWM4_DriveMode_1_ADDR:	0x109
BYTE			PWM4_DriveMode_1_ADDR;
#pragma	ioport	PWM4_DriveMode_2_ADDR:	0xb
BYTE			PWM4_DriveMode_2_ADDR;
#pragma	ioport	PWM4_GlobalSelect_ADDR:	0xa
BYTE			PWM4_GlobalSelect_ADDR;
#pragma	ioport	PWM4_IntCtrl_0_ADDR:	0x10a
BYTE			PWM4_IntCtrl_0_ADDR;
#pragma	ioport	PWM4_IntCtrl_1_ADDR:	0x10b
BYTE			PWM4_IntCtrl_1_ADDR;
#pragma	ioport	PWM4_IntEn_ADDR:	0x9
BYTE			PWM4_IntEn_ADDR;
#define PWM4_MASK 0x80
