from body_pause import BodyPause
from feet_velocities import FeetVelocities
from rotate_feet_about_origin import RotateFeetAboutOrigin
from trapezoidal_feet_align import TrapezoidalFeetAlign
from trapezoidal_feet_lift_lower import TrapezoidalFeetLiftLower
from trapezoidal_sit_stand import TrapezoidalSitStand
from tripod_gait import TripodGait
from go_to_standard_hexagon import GoToStandardHexagon