/******************************************************************************
*  Generated by PSoC Designer 5.2.2401
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "ADCINC.h"
#include "DAC6.h"
#include "PGA_1.h"
#include "PWM8.h"
#include "UART.h"

#endif
