/******************************************************************************
*  Generated by PSoC Designer 5.1.2306
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "PWM8_1.h"
#include "PWM8_2.h"
#include "UART.h"

#endif
