/******************************************************************************
*  Generated by PSoC Designer 5.2.2551
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "PWM8_1.h"
#include "PWM8_2.h"
#include "SleepTimer_1.h"
#include "UART.h"

#endif
