//*****************************************************************************
//*****************************************************************************
//  FILENAME: DAC6.h
//   Version: 4.3, Updated on 2011/6/28 at 6:9:3
//  Generated by PSoC Designer 5.1.2306
//
//  DESCRIPTION:  DAC6 User Module C Language interface file.
//
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2011. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef DAC6_INCLUDE
#define DAC6_INCLUDE

#include <M8C.h>

//-------------------------------------------------
// Defines for DAC6 API's.
//-------------------------------------------------
#define DAC6_OFF         0
#define DAC6_LOWPOWER    1
#define DAC6_MEDPOWER    2
#define DAC6_HIGHPOWER   3
#define DAC6_FULLPOWER   3

#pragma fastcall16 DAC6_Start
#pragma fastcall16 DAC6_SetPower
#pragma fastcall16 DAC6_WriteBlind
#pragma fastcall16 DAC6_WriteStall
#pragma fastcall16 DAC6_Stop

//-------------------------------------------------
// Prototypes of the DAC6 API.
//-------------------------------------------------
extern void DAC6_Start(BYTE bPowerSetting);
extern void DAC6_SetPower(BYTE bPowerSetting);
extern void DAC6_WriteBlind(CHAR cOutputValue);
extern void DAC6_WriteStall(CHAR cOutputValue);
extern void DAC6_Stop(void);


//-------------------------------------------------
// Register Addresses for DAC6
//-------------------------------------------------
#pragma ioport  DAC6_CR0:   0x084
BYTE            DAC6_CR0;
#pragma ioport  DAC6_CR1:   0x085
BYTE            DAC6_CR1;
#pragma ioport  DAC6_CR2:   0x086
BYTE            DAC6_CR2;
#pragma ioport  DAC6_CR3:   0x087
BYTE            DAC6_CR3;

#endif
// end of file DAC6.h
