# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='robotState.proto',
  package='UI',
  serialized_pb='\n\x10robotState.proto\x12\x02UI\"\xba\x02\n\x05State\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12 \n\x04legs\x18\n \x03(\x0b\x32\x12.UI.State.LegState\x1a\x80\x02\n\x08LegState\x12\x17\n\x0fhip_yaw_command\x18\x01 \x01(\x01\x12\x19\n\x11hip_pitch_command\x18\x02 \x01(\x01\x12\x1a\n\x12knee_pitch_command\x18\x03 \x01(\x01\x12\x15\n\rhip_yaw_angle\x18\x04 \x01(\x01\x12\x17\n\x0fhip_pitch_angle\x18\x05 \x01(\x01\x12\x18\n\x10knee_pitch_angle\x18\x06 \x01(\x01\x12\x13\n\x0bshock_depth\x18\x07 \x01(\x01\x12\x14\n\x0chip_yaw_rate\x18\x08 \x01(\x01\x12\x16\n\x0ehip_pitch_rate\x18\t \x01(\x01\x12\x17\n\x0fknee_pitch_rate\x18\n \x01(\x01')




_STATE_LEGSTATE = descriptor.Descriptor(
  name='LegState',
  full_name='UI.State.LegState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hip_yaw_command', full_name='UI.State.LegState.hip_yaw_command', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hip_pitch_command', full_name='UI.State.LegState.hip_pitch_command', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='knee_pitch_command', full_name='UI.State.LegState.knee_pitch_command', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hip_yaw_angle', full_name='UI.State.LegState.hip_yaw_angle', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hip_pitch_angle', full_name='UI.State.LegState.hip_pitch_angle', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='knee_pitch_angle', full_name='UI.State.LegState.knee_pitch_angle', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shock_depth', full_name='UI.State.LegState.shock_depth', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hip_yaw_rate', full_name='UI.State.LegState.hip_yaw_rate', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hip_pitch_rate', full_name='UI.State.LegState.hip_pitch_rate', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='knee_pitch_rate', full_name='UI.State.LegState.knee_pitch_rate', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=83,
  serialized_end=339,
)

_STATE = descriptor.Descriptor(
  name='State',
  full_name='UI.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='time', full_name='UI.State.time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='legs', full_name='UI.State.legs', index=1,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_STATE_LEGSTATE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=339,
)

_STATE_LEGSTATE.containing_type = _STATE;
_STATE.fields_by_name['legs'].message_type = _STATE_LEGSTATE
DESCRIPTOR.message_types_by_name['State'] = _STATE

class State(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class LegState(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _STATE_LEGSTATE
    
    # @@protoc_insertion_point(class_scope:UI.State.LegState)
  DESCRIPTOR = _STATE
  
  # @@protoc_insertion_point(class_scope:UI.State)

# @@protoc_insertion_point(module_scope)
