# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='robotControl.proto',
  package='UI',
  serialized_pb='\n\x12robotControl.proto\x12\x02UI\"8\n\x07\x43ommand\x12\x13\n\x0braw_command\x18\x01 \x01(\t\x12\x18\n\x10intended_command\x18\x02 \x01(\t')




_COMMAND = descriptor.Descriptor(
  name='Command',
  full_name='UI.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='raw_command', full_name='UI.Command.raw_command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='intended_command', full_name='UI.Command.intended_command', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['Command'] = _COMMAND

class Command(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMAND
  
  # @@protoc_insertion_point(class_scope:UI.Command)

# @@protoc_insertion_point(module_scope)
